### ISSUE TITLE
Rosalind answers should not be posted to the internet

### ISSUE THREAD

**Issue by davmlaw** [guillermo-carrasco/rosalind#1]
In the FAQ:

http://rosalind.info/faq/#can-i-post-my-solutions-somewhere

>> Can I post my solutions somewhere?

No.

Please make your repository private or remove it from the internet as it is violating the Rosalind licence. Thanks

**Comment by guillermo-carrasco** [comment]
Hi @davmlaw ,

First of all, there is no such a "license" that I am violating. What I am "violating" are some recommendations. This is true, but I can argue why:

1. I have done a short search for the word "rosalind" in GitHub and I've found a couple of tens of repositories with solutions, you have opened this issue here, but closing this repository or making it private is not going to change anything, you will always have, and cannot control, public repositories with solutions.
2. I am not redirecting to anyone here, no comments pointing to this repository on rosalind or anywhere else. If someone arrives here is because they are looking for solutions or inspiration. 
3. Looking at other's code _is not a bad practice_, if fact I think is the best way to learn both a programming language and problem solving. It **is** a bad practice to copy & paste a solution without understanding it, but **that is the responsibility of the person that does that**, not mine. 
4. Going back to point 3, responsible students that really want to learn are not going to copy & paste a solution. They are going to look for other people's implementations when they have solved the problem themselves.
5. On that same FAQ, they say:

    > Once you have solved a problem, then we encourage you to post your code to the problem's comments section (which can be seen only by users who have also solved the problem).

    I don't see any difference on posting it on the comments or on GitHub. As I say, if someone wants a solution before solving a problem, they are going to get it somehow.

I hope that I have made my point clear: I don't believe in barriers on learning, and **I do believe** on people's reasonableness.

**Comment by davmlaw** [comment]
Hi I found your repo as it was the top hut while googling for a question for my student.

Sorry it was not a license, just a request from them and they said please not to do it.

**Comment by mikheyev** [comment]
Hi @guillermo-carrasco,

As an educator who uses Rosalind for class I can assure you that your repo makes my life more difficult. You are maintaining a giant repository of cheats, which I have to cross check when my students turn in what is supposed to be their work. I understand your beliefs, but please also understand that Rosalind is not just for you, and that your actions affect other people.

Please allow me rebut your five-point argument above. It has questions, but they are rhetorical and I do not wish to engage you in a debate:

1. Yes, there are other Rosalind repositories. "Others are doing it" does not make something right. Also, how many of the other repository owners have been repeatedly asked to take their repositories down and refused?
2. Yes, but your repository comes up first when someone googles "rosalind github". This must come with some kind of responsibility. Regardless of that, just because you don't go out of your way to make this information easy to find does not make it a good thing to do.
3. Looking at others code is excellent practice, which is why Rosalind encourages you to submit it and comment on others people's code. Your repo does not prevent this process from happening. Providing ready-made solutions, though lowers the barrier to cheating. "They shouldn't be cheating in the first place" argument does not work in the real world. Trust me.
4. True enough, but why make it easier for them? By lowering the barrier to cheating you are (a) hurting the weaker students and (b) taking my time for weeding them out. Is this the effect you want to have? What is the benefit to *you* of keeping this information public?
5. Rosalind explicitly asks you not to do what you are doing. There is no way to counter-argue this. You may not feel there is a difference between posting in Rosalind's comments when you've solved the problem and posting it here, but there is one. Information has scope and context. It is the same difference between me knowing your personal address and phone number, and me posting them here. Although, sentiment that "the kind people at Rosalind who took their time to make the site that I enjoyed asked me not to this"  should really be enough for you.

I don't expect that my comments will sway you. That's not how the internet works. I'll let you mull this over for a few days, and then I'll contact rosalind, github and your employer to see if they can help.

**Comment by guillermo-carrasco** [comment]
Hi @davmlaw and @mikheyev ,

Okay... I still think that you are wrong chasing repositories like mine, and I think that your efforts should be canalised to teaching your students not to cheat and encouraging them to learn from others after they've tried hard. Also, even if they don't do that, I don't think that these problems are their whole evaluation, and they'll have troubles on a real tests if they didn't do the problems themselves.

Nonetheless... 

> "Others are doing it" does not make something right. Also, how many of the other repository owners have been repeatedly asked to take their repositories down and refused?

and 

> Rosalind explicitly asks you not to do what you are doing. There is no way to counter-argue this.

are true statements, so I'll shut down the repo just because I don't want any trouble with anyone. I just hope you realize that this is not gonna help anyone. 

Cheers,
